### ISSUE TITLE
Add ability to update server build configuration

### ISSUE THREAD

**Issue by Wallvon** [iamkubi/pydactyl#11] opened 2020-08-02 22:00 UTC
Hi there,

Pydactyl has been lovely so far, but, I hit 1 roadblock when using it, and that is that I cannot change the resources of the server. I really need this since my users want to change their RAM, CPU or Storage, but they can't. It would be greatly appreciated if you could add it to the package.

Thanks,
Robert S.

**Comment by iamkubi** [comment] 2020-08-02 22:55
Duplicate of #9

**Closed by iamkubi** 2020-08-02 22:55 UTC
